// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001213847_AddReportCurrency")]
    partial class AddReportCurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Domain.BudgetLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BudgetLines", (string)null);
                });

            modelBuilder.Entity("Domain.BudgetTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BudgetLineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BudgetLineId", "Name")
                        .IsUnique();

                    b.ToTable("BudgetTags", (string)null);
                });

            modelBuilder.Entity("Domain.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Domain.CurrencyDefaultSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DocumentCurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReportCurrencyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DocumentCurrencyId");

                    b.HasIndex("ReportCurrencyId");

                    b.ToTable("CurrencyDefaultSettings", (string)null);
                });

            modelBuilder.Entity("Domain.ExpenseDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("ExpenseDocuments");
                });

            modelBuilder.Entity("Domain.ExpenseDocumentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("BudgetLineId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BudgetTagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpenseDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BudgetLineId");

                    b.HasIndex("BudgetTagId");

                    b.HasIndex("ExpenseDocumentId");

                    b.ToTable("ExpenseDocumentItems");
                });

            modelBuilder.Entity("Domain.JsonImportPromptSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalInstructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JsonImportPromptSettings", (string)null);
                });

            modelBuilder.Entity("Domain.BudgetTag", b =>
                {
                    b.HasOne("Domain.BudgetLine", "BudgetLine")
                        .WithMany()
                        .HasForeignKey("BudgetLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetLine");
                });

            modelBuilder.Entity("Domain.CurrencyDefaultSettings", b =>
                {
                    b.HasOne("Domain.Currency", null)
                        .WithMany()
                        .HasForeignKey("DocumentCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Currency", null)
                        .WithMany()
                        .HasForeignKey("ReportCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("Domain.CurrencyValue", "CurrencyValues", b1 =>
                        {
                            b1.Property<int>("SettingsId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CurrencyId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Value")
                                .HasColumnType("TEXT");

                            b1.HasKey("SettingsId", "CurrencyId");

                            b1.HasIndex("CurrencyId");

                            b1.ToTable("DefaultCurrencyValues", (string)null);

                            b1.HasOne("Domain.Currency", null)
                                .WithMany()
                                .HasForeignKey("CurrencyId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("SettingsId");
                        });

                    b.Navigation("CurrencyValues");
                });

            modelBuilder.Entity("Domain.ExpenseDocument", b =>
                {
                    b.HasOne("Domain.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("Domain.CurrencyValue", "CurrencyValues", b1 =>
                        {
                            b1.Property<int>("ExpenseDocumentId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CurrencyId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Value")
                                .HasColumnType("TEXT");

                            b1.HasKey("ExpenseDocumentId", "CurrencyId");

                            b1.HasIndex("CurrencyId");

                            b1.ToTable("ExpenseDocumentCurrencyValues", (string)null);

                            b1.HasOne("Domain.Currency", null)
                                .WithMany()
                                .HasForeignKey("CurrencyId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ExpenseDocumentId");
                        });

                    b.Navigation("CurrencyValues");
                });

            modelBuilder.Entity("Domain.ExpenseDocumentItem", b =>
                {
                    b.HasOne("Domain.BudgetLine", "BudgetLine")
                        .WithMany()
                        .HasForeignKey("BudgetLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.BudgetTag", "BudgetTag")
                        .WithMany()
                        .HasForeignKey("BudgetTagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.ExpenseDocument", "ExpenseDocument")
                        .WithMany("Items")
                        .HasForeignKey("ExpenseDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetLine");

                    b.Navigation("BudgetTag");

                    b.Navigation("ExpenseDocument");
                });

            modelBuilder.Entity("Domain.ExpenseDocument", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
