// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260823185738_AddJsonImportPromptSettings")]
    partial class AddJsonImportPromptSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Domain.BudgetLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BudgetLines", (string)null);
                });

            modelBuilder.Entity("Domain.BudgetTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BudgetLineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BudgetLineId", "Name")
                        .IsUnique();

                    b.ToTable("BudgetTags", (string)null);
                });

            modelBuilder.Entity("Domain.ExpenseDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExpenseDocuments");
                });

            modelBuilder.Entity("Domain.ExpenseDocumentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("BudgetLineId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BudgetTagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpenseDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BudgetLineId");

                    b.HasIndex("BudgetTagId");

                    b.HasIndex("ExpenseDocumentId");

                    b.ToTable("ExpenseDocumentItems");
                });

            modelBuilder.Entity("Domain.JsonImportPromptSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalInstructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JsonImportPromptSettings", (string)null);
                });

            modelBuilder.Entity("Domain.BudgetTag", b =>
                {
                    b.HasOne("Domain.BudgetLine", "BudgetLine")
                        .WithMany()
                        .HasForeignKey("BudgetLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetLine");
                });

            modelBuilder.Entity("Domain.ExpenseDocumentItem", b =>
                {
                    b.HasOne("Domain.BudgetLine", "BudgetLine")
                        .WithMany()
                        .HasForeignKey("BudgetLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.BudgetTag", "BudgetTag")
                        .WithMany()
                        .HasForeignKey("BudgetTagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.ExpenseDocument", "ExpenseDocument")
                        .WithMany("Items")
                        .HasForeignKey("ExpenseDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetLine");

                    b.Navigation("BudgetTag");

                    b.Navigation("ExpenseDocument");
                });

            modelBuilder.Entity("Domain.ExpenseDocument", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
